/**
 * recipes.js — seed data for Baker's Delight.
 *
 * Every recipe from the original vanilla HTML/CSS/JS project is preserved here.
 * This becomes the source of truth for the MongoDB database.
 *
 * Categories: dessert | breakfast | lunch
 * Audiences:  family | friend | romantic
 */

const desserts = [
  {
    title: 'Chocolate Chip Cookies',
    category: 'dessert',
    description: 'Classic, golden-edged cookies packed with chocolate chips. The benchmark bake.',
    joke: "These cookies hit harder than a final boss. You've been warned.",
    meaning: 'Comfort and care. The classic way of saying "I was thinking about you."',
    prepTime: '15 min',
    cookTime: '12 min',
    audiences: ['family', 'friend', 'romantic'],
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&h=300&fit=crop',
    ingredients: [
      '2¼ cups all-purpose flour',
      '1 tsp baking soda',
      '1 tsp salt',
      '1 cup butter, softened',
      '¾ cup granulated sugar',
      '¾ cup packed brown sugar',
      '2 large eggs',
      '2 tsp vanilla extract',
      '2 cups chocolate chips',
    ],
    steps: [
      'Preheat oven to 375°F (190°C) and line your baking sheets.',
      'Beat butter and both sugars together until light and fluffy.',
      'Beat in eggs and vanilla.',
      'Gradually mix in flour, baking soda and salt.',
      'Stir in the chocolate chips.',
      'Drop rounded tablespoons onto baking sheets.',
      'Bake 9 to 11 minutes until golden. Let cool — patience is a skill.',
    ],
  },
  {
    title: 'Lava Cake',
    category: 'dessert',
    description: 'Individual chocolate cakes with a gloriously molten centre. Built for special moments.',
    joke: 'The molten centre is basically the plot twist of desserts — you never see it coming.',
    meaning: 'Passion that runs deep. Warm on the inside even when it looks composed on the outside.',
    prepTime: '20 min',
    cookTime: '12 min',
    audiences: ['romantic', 'friend'],
    image: 'https://images.unsplash.com/photo-1617305855105-3e86f65e7893?w=500&h=300&fit=crop',
    ingredients: [
      '200g dark chocolate',
      '100g butter',
      '3 eggs and 3 yolks',
      '100g icing sugar',
      '60g flour',
      'Pinch of salt',
    ],
    steps: [
      'Preheat oven to 200°C. Butter and flour 4 ramekins.',
      'Melt chocolate and butter together. Let it cool slightly.',
      'Whisk eggs, yolks and sugar until pale.',
      'Fold chocolate mixture into eggs, then fold in flour.',
      'Fill ramekins three quarters full.',
      'Bake 10 to 12 minutes — edges set, centre still jiggles.',
      'Rest 1 minute then invert onto a plate. Serve immediately.',
    ],
  },
  {
    title: 'Fudgy Brownies',
    category: 'dessert',
    description: 'Dense, rich, deeply chocolatey brownies with clean edges when properly cooled.',
    joke: 'Dense, dark, and dangerously addictive. One piece? Impossible. Mythical even.',
    meaning: 'No-nonsense goodness. Proof that sometimes simple is best.',
    prepTime: '15 min',
    cookTime: '25 min',
    audiences: ['family', 'friend', 'romantic'],
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&h=300&fit=crop',
    ingredients: [
      '170g dark chocolate, chopped',
      '115g butter',
      '200g sugar',
      '2 large eggs',
      '1 tsp vanilla',
      '50g cocoa powder',
      '65g flour',
      '¼ tsp salt',
    ],
    steps: [
      'Preheat oven to 175°C and line a 8x8 inch pan with parchment paper.',
      'Melt chocolate and butter together over low heat.',
      'Whisk sugar, eggs and vanilla until combined.',
      'Fold chocolate mixture into eggs. Sift cocoa, flour and salt over top and fold gently.',
      'Pour into prepared pan and bake 20 to 25 minutes.',
      'Cool completely before cutting. Patience rewards you with clean edges.',
    ],
  },
  {
    title: 'Classic Cheesecake',
    category: 'dessert',
    description: 'Creamy New York-style cheesecake on a buttery digestive biscuit base.',
    joke: 'Creamy, dreamy, and worth every second of the 8-hour chill time.',
    meaning: "You're willing to invest time for excellence. That's love language right there.",
    prepTime: '30 min',
    cookTime: '55 min',
    audiences: ['romantic', 'family'],
    image: 'https://images.unsplash.com/photo-1589985643453-f67d165c1c03?w=500&h=300&fit=crop',
    ingredients: [
      '200g digestive biscuits, crushed',
      '100g melted butter',
      '800g cream cheese, softened',
      '200g sugar',
      '4 large eggs',
      '1 tsp vanilla',
      '2 tbsp cornstarch',
    ],
    steps: [
      'Preheat oven to 160°C. Mix biscuits and melted butter, press into a 9-inch springform pan.',
      'Beat cream cheese and sugar until smooth. Add eggs one at a time, then vanilla.',
      'Fold in cornstarch and pour over crust.',
      'Bake 50 to 55 minutes until center is just set. Cool slowly — sudden temperature changes crack the surface.',
      'Chill for at least 8 hours before serving.',
    ],
  },
];

const breakfast = [
  {
    title: 'Fluffy Pancakes',
    category: 'breakfast',
    description: 'Light, tall, golden pancakes. The kind that make a Sunday feel like a reward.',
    joke: 'Making these before 9am? You are the protagonist. Everyone else is NPC.',
    meaning: 'A soft layered effort. The kind that says "I woke up early because you matter."',
    prepTime: '10 min',
    cookTime: '15 min',
    audiences: ['family', 'romantic'],
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=500&h=300&fit=crop',
    ingredients: [
      '1½ cups flour',
      '3½ tsp baking powder',
      '1 tbsp sugar',
      '¼ tsp salt',
      '1¼ cups milk',
      '1 egg',
      '3 tbsp melted butter',
      '1 tsp vanilla',
    ],
    steps: [
      'Sift all your dry ingredients into a bowl.',
      'Make a well in the middle and pour in the milk, egg, butter and vanilla. Mix until just combined — lumps are fine.',
      'Let the batter rest for 5 minutes. This is the secret checkpoint.',
      'Cook on medium heat, a quarter cup per pancake. Flip when bubbles form on the surface.',
      'Stack high and serve with syrup, berries or whatever your side quest requires.',
    ],
  },
  {
    title: 'Banana Bread',
    category: 'breakfast',
    description: 'Moist, golden loaf that transforms overripe bananas into something worth waking up for.',
    joke: 'Those overripe bananas were not a mistake. They were training for this moment.',
    meaning: 'Turning something past its prime into something beautiful. A second chance baked into a loaf.',
    prepTime: '15 min',
    cookTime: '60 min',
    audiences: ['family', 'friend'],
    image: 'https://images.unsplash.com/photo-1606101273945-64a4c32c8d5a?w=500&h=300&fit=crop',
    ingredients: [
      '3 ripe bananas, mashed',
      '⅓ cup melted butter',
      '¾ cup sugar',
      '1 egg beaten',
      '1 tsp vanilla',
      '1½ cups flour',
      '1 tsp baking soda',
      'Pinch of salt',
    ],
    steps: [
      'Preheat oven to 175°C and grease a loaf tin.',
      'Mix the melted butter into the mashed banana.',
      'Stir in the sugar, egg and vanilla.',
      'Mix in the flour, baking soda and salt. Don\'t overmix.',
      'Pour into the tin and bake 55 to 65 minutes until a toothpick comes out clean.',
      'Cool before slicing. The wait builds character.',
    ],
  },
  {
    title: 'Cinnamon French Toast',
    category: 'breakfast',
    description: 'Egg-soaked bread fried golden with cinnamon and vanilla. Quick, warm, and satisfying.',
    joke: 'Stale bread just got a glow up. This is what redemption looks like.',
    meaning: 'Turning the ordinary into something special with very little. A reminder that effort changes everything.',
    prepTime: '5 min',
    cookTime: '10 min',
    audiences: ['family', 'romantic'],
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=500&h=300&fit=crop',
    ingredients: [
      '4 slices of bread',
      '2 eggs',
      '¼ cup milk',
      '1 tsp cinnamon',
      '1 tsp vanilla',
      '1 tbsp sugar',
      'Butter for the pan',
    ],
    steps: [
      'Whisk eggs, milk, cinnamon, vanilla and sugar together in a shallow bowl.',
      'Dip each slice of bread into the mixture and let it soak for a few seconds on each side.',
      'Melt butter in a pan over medium heat.',
      'Cook each slice 2 to 3 minutes per side until golden.',
      'Serve with syrup, fruit or powdered sugar.',
    ],
  },
  {
    title: 'Blueberry Muffins',
    category: 'breakfast',
    description: 'Bakery-style muffins bursting with blueberries. More cake than muffin — no judgement.',
    joke: 'More cake than muffin, but we don\'t judge delicious decisions.',
    meaning: '"I thought of you this morning." A grab-and-go care package.',
    prepTime: '10 min',
    cookTime: '22 min',
    audiences: ['family', 'friend'],
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&h=300&fit=crop',
    ingredients: [
      '2 cups flour',
      '½ cup sugar',
      '2½ tsp baking powder',
      '½ tsp salt',
      '1 egg',
      '1 cup milk',
      '⅓ cup melted butter',
      '1½ cups fresh blueberries',
    ],
    steps: [
      'Preheat oven to 200°C and line a muffin tin with paper cases.',
      'Mix flour, sugar, baking powder and salt in a large bowl.',
      'Whisk egg, milk and butter together, then fold into dry ingredients.',
      'Gently fold in blueberries — don\'t overmix the batter.',
      'Fill cases three-quarters full and bake 20 to 22 minutes until golden.',
    ],
  },
  {
    title: 'Strawberry Shortcake',
    category: 'breakfast',
    description: 'Fluffy biscuit rounds layered with whipped cream and sweet macerated strawberries.',
    joke: 'Light, fluffy, and covered in berries. Summer in cake form.',
    meaning: '"Let\'s make this moment special." Celebration energy.',
    prepTime: '20 min',
    cookTime: '18 min',
    audiences: ['family', 'romantic'],
    image: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=500&h=300&fit=crop',
    ingredients: [
      '1¾ cups flour',
      '4 tsp baking powder',
      '½ tsp salt',
      '5 tbsp sugar, divided',
      '6 tbsp cold butter',
      '¾ cup milk',
      '500g fresh strawberries, sliced',
      '250ml whipped cream',
    ],
    steps: [
      'Preheat oven to 200°C and line a baking tray.',
      'Mix flour, baking powder, salt and 4 tbsp sugar. Rub in cold butter until breadcrumbs form.',
      'Add milk and mix gently to form a soft dough. Pat into 2cm thickness and cut into rounds.',
      'Bake 15 to 18 minutes until golden. Cool slightly.',
      'Toss strawberries with remaining sugar, let sit 15 minutes to release juices.',
      'Split shortcakes, layer with whipped cream and strawberries.',
    ],
  },
];

const lunch = [
  {
    title: 'Bacon & Cheese Quiche',
    category: 'lunch',
    description: 'A golden shortcrust pastry tart filled with crispy bacon, cheddar and silky egg custard.',
    joke: 'Balanced, like all things should be. Thanos would approve.',
    meaning: 'Steady, dependable effort. The kind of care that shows up on a normal Tuesday, not just special occasions.',
    prepTime: '20 min',
    cookTime: '35 min',
    audiences: ['family', 'friend'],
    image: 'https://images.unsplash.com/photo-1582456891866-8c1d6d5c1d9a?w=500&h=300&fit=crop',
    ingredients: [
      '1 pre-made shortcrust pastry base',
      '150g bacon, chopped',
      '1 cup grated cheddar',
      '4 large eggs',
      '1 cup cream',
      'Salt and pepper to taste',
      'Chopped chives, optional',
    ],
    steps: [
      'Preheat oven to 180°C and line the pastry base into a tart tin.',
      'Fry the bacon until crisp, then scatter it over the pastry base along with the cheese.',
      'Whisk eggs, cream, salt and pepper together.',
      'Pour the egg mixture over the bacon and cheese.',
      'Bake 30 to 35 minutes until set and golden on top.',
      'Rest 5 minutes before slicing. Respawn timer, basically.',
    ],
  },
  {
    title: 'Spinach & Feta Rolls',
    category: 'lunch',
    description: 'Flaky puff pastry rolls stuffed with spinach, crumbled feta and a pinch of nutmeg.',
    joke: 'Green stat boost included. No side effects, just flaky pastry.',
    meaning: 'Small effort, shareable results. The friend who always brings snacks to the party.',
    prepTime: '15 min',
    cookTime: '20 min',
    audiences: ['friend', 'family'],
    image: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=500&h=300&fit=crop',
    ingredients: [
      '1 sheet ready-rolled puff pastry',
      '200g frozen spinach, thawed and squeezed dry',
      '150g feta, crumbled',
      '1 egg, beaten (for wash)',
      'Pinch of nutmeg',
      'Salt and pepper to taste',
    ],
    steps: [
      'Preheat oven to 200°C and line a baking tray.',
      'Mix the spinach, feta, nutmeg, salt and pepper in a bowl.',
      'Spread the mixture along one edge of the pastry sheet and roll it up into a log.',
      'Slice into rounds about 3cm thick and place on the tray.',
      'Brush with egg wash.',
      'Bake 18 to 20 minutes until puffed and golden.',
    ],
  },
  {
    title: 'Savoury Herb Scones',
    category: 'lunch',
    description: 'Fluffy, golden scones packed with cheddar and mixed herbs. Ready in under 30 minutes.',
    joke: 'Fast to make, satisfying to eat. The speedrun of lunch bakes.',
    meaning: 'Quick thinking under pressure. You didn\'t have much time, but you still showed up properly.',
    prepTime: '10 min',
    cookTime: '18 min',
    audiences: ['friend', 'family'],
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd0ea1d?w=500&h=300&fit=crop',
    ingredients: [
      '2 cups self-raising flour',
      '60g cold butter, cubed',
      '¾ cup milk',
      '½ cup grated cheddar',
      '2 tbsp chopped mixed herbs',
      'Pinch of salt',
    ],
    steps: [
      'Preheat oven to 220°C and line a baking tray.',
      'Rub the cold butter into the flour and salt until it looks like breadcrumbs.',
      'Stir in the cheese and herbs.',
      'Add the milk and mix gently until just combined. Don\'t overwork the dough.',
      'Pat out to about 3cm thick and cut into rounds.',
      'Bake 15 to 18 minutes until risen and golden.',
    ],
  },
  {
    title: 'Olive & Tomato Focaccia',
    category: 'lunch',
    description: 'Dimpled Italian flatbread topped with olives, cherry tomatoes, garlic and rosemary.',
    joke: "Crispy outside, fluffy inside. The Mediterranean's love letter to bread.",
    meaning: 'Bringing warmth to the table. Simple ingredients, complex flavors, pure generosity.',
    prepTime: '20 min',
    cookTime: '25 min',
    audiences: ['family', 'friend'],
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=500&h=300&fit=crop',
    ingredients: [
      '500g bread dough (store-bought or homemade)',
      '3 tbsp olive oil',
      '100g pitted olives, halved',
      '150g cherry tomatoes, halved',
      '3 cloves garlic, minced',
      '1 tsp dried rosemary',
      'Salt and cracked pepper to taste',
    ],
    steps: [
      'Preheat oven to 200°C and oil a baking tray.',
      'Press dough onto the tray, dimpling the surface with your fingertips.',
      'Brush with olive oil. Scatter olives, tomatoes and garlic over top.',
      'Sprinkle with rosemary, salt and pepper.',
      'Bake 22 to 25 minutes until golden and crispy.',
      'Serve warm with extra olive oil for dipping.',
    ],
  },
  {
    title: 'Caprese Pizza',
    category: 'lunch',
    description: 'A simple, elegant pizza with tomato sauce, fresh mozzarella, ripe tomatoes and basil.',
    joke: 'Tomato, mozzarella, basil. Sometimes the simplest combos are the most powerful.',
    meaning: '"I respect your palate enough to keep it simple." Quality over quantity.',
    prepTime: '15 min',
    cookTime: '15 min',
    audiences: ['friend', 'romantic'],
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500&h=300&fit=crop',
    ingredients: [
      '1 pizza base (store-bought or homemade)',
      '150ml tomato sauce or passata',
      '250g fresh mozzarella, torn',
      '3 ripe tomatoes, sliced',
      'Fresh basil leaves',
      '2 tbsp olive oil',
      'Salt and cracked pepper',
    ],
    steps: [
      'Preheat oven to 220°C and place pizza base on a baking tray.',
      'Spread tomato sauce over the base, leaving a border for the crust.',
      'Scatter mozzarella and tomato slices over the sauce.',
      'Drizzle with olive oil and season with salt and pepper.',
      'Bake 12 to 15 minutes until crust is golden and cheese is bubbly.',
      'Top with fresh basil and serve immediately.',
    ],
  },
  {
    title: 'Garlic Knots',
    category: 'lunch',
    description: 'Soft, buttery dough knots brushed with garlic, parsley and Parmesan. Crowd-pleasers every time.',
    joke: 'Carb-loaded and butter-drenched. Everything a victory should taste like.',
    meaning: 'Showing up for people who matter. No pretense, just delicious.',
    prepTime: '10 min',
    cookTime: '12 min',
    audiences: ['family', 'friend'],
    image: 'https://images.unsplash.com/photo-1565958011457-acf109c5c869?w=500&h=300&fit=crop',
    ingredients: [
      '1 can crescent roll dough',
      '4 tbsp butter, melted',
      '4 cloves garlic, minced',
      '2 tbsp fresh parsley, chopped',
      '½ tsp garlic powder',
      '¼ tsp salt',
      'Parmesan cheese, grated',
    ],
    steps: [
      'Preheat oven to 190°C and line a baking tray.',
      'Unroll crescent dough and separate along perforations.',
      'Mix melted butter with minced garlic, parsley, garlic powder and salt.',
      'Brush mixture over dough pieces. Roll and tie each piece into a knot.',
      'Place on tray and bake 10 to 12 minutes until golden.',
      'Sprinkle with Parmesan while warm. Serve immediately.',
    ],
  },
];

module.exports = { desserts, breakfast, lunch };
